<%@ Page Title="" Language="C#" MasterPageFile="~/Masters/AdminDashboardMain.master" AutoEventWireup="true" CodeBehind="JuegosXTiendasDashboard.aspx.cs" Inherits="Vistas.JuegosXTiendasDashboard" %>

<asp:Content ID="Content1" ContentPlaceHolderID="adminDashboardContent" runat="server">
    <%-- Aca van mensajes --%>
    <asp:Label ID="lblMsg" runat="server"></asp:Label>
    <div class="input-group input-cat">
        <div class="form-outline">
            <asp:TextBox runat="server" class="form-control bg-dark text-light no-borders" ID="txtSearchGamesxstores" placeholder="Buscar juegosXTiendas"></asp:TextBox>
        </div>
        <asp:Button runat="server" CssClass="btn btn-primary" Text="Buscar" OnClick="BtnSearch_Click"></asp:Button>
    </div>
    <asp:GridView ID="GridViewGamesXStores"
        runat="server"
        AutoGenerateEditButton="True"
        CssClass="grd-user w-100 bg-dark-carbon ctrl-gamesxstores"
        AutoGenerateColumns="False"
        OnRowCancelingEdit="GridViewGamesXStores_RowCancelingEdit"
        OnRowEditing="GridViewGamesXStores_RowEditing"
        OnRowUpdating="GridViewGamesXStores_RowUpdating"
        OnRowDeleting="GridViewGamesXStores_RowDeleting"
        ShowFooter="true"
        AllowPaging="True" AutoGenerateDeleteButton="True">
        <Columns>
            <asp:TemplateField HeaderText="Juego">
                <EditItemTemplate>
                    <asp:Label ID="lblGVGamesXStoresJuego" runat="server" Text='<%# Bind("Juego") %>'>
                    </asp:Label>
                    <asp:HiddenField ID="hfGVGamesXStoresJuego" runat="server" Value='<%# Bind("IdJuego") %>' />
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblGVGamesXStoresJuego" runat="server" Text='<%# Bind("Juego") %>'>
                    </asp:Label>
                    <asp:HiddenField ID="hfGVGamesXStoresJuego" runat="server" Value='<%# Bind("IdJuego") %>' />
                </ItemTemplate>
                <FooterTemplate>
                    <asp:DropDownList ID="ddlGVGamesXStoresJuego" runat="server"></asp:DropDownList>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Tienda">
                <EditItemTemplate>
                    <asp:Label ID="lblGVGamesXStoresTienda" runat="server" Text='<%# Bind("Tienda") %>'>
                    </asp:Label>
                    <asp:HiddenField ID="hfGVGamesXStoresTienda" runat="server" Value='<%# Bind("IdTienda") %>' />
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblGVGamesXStoresTienda" runat="server" Text='<%# Bind("Tienda") %>'>
                    </asp:Label>
                    <asp:HiddenField ID="hfGVGamesXStoresTienda" runat="server" Value='<%# Bind("IdTienda") %>' />
                </ItemTemplate>
                <FooterTemplate>
                    <asp:DropDownList ID="ddlGVGamesXStoresTienda" runat="server"></asp:DropDownList>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="URL">
                <EditItemTemplate>
                    <asp:TextBox ID="txtGVGamesXStoresURL" runat="server" Text='<%# Eval("URL") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblGVGamesXStoresURL" runat="server" Text='<%# Eval("URL") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtGVGamesXStoresURL" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Precio">
                <EditItemTemplate>
                    <asp:TextBox ID="txtGVGamesXStoresPrecio" runat="server" Text='<%# Eval("Precio") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblGVGamesXStoresPrecio" runat="server" Text='<%# Eval("Precio") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtGVGamesXStoresPrecio" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="PrecioRebajado">
                <EditItemTemplate>
                    <asp:TextBox ID="txtGVGamesXStoresPrecioRebajado" runat="server" Text='<%# Eval("Precio Rebajado") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="lblGVGamesXStoresPrecioRebajado" runat="server" Text='<%# Eval("Precio Rebajado") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="txtGVGamesXStoresPrecioRebajado" runat="server"></asp:TextBox>
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Activo">
                <EditItemTemplate>
                    <asp:CheckBox ID="chkGVGamesXStoresActivo" runat="server" Checked='<%# Eval("Activo") %>' />
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:CheckBox ID="chkGVGamesXStoresActivo" runat="server" Checked='<%# Eval("Activo") %>' Enabled="False" />
                </ItemTemplate>
                <FooterTemplate>
                    <asp:LinkButton ID="btnGVGamesXStoresAgregar" runat="server" OnClick="btnGVGamesXStoresAgregar_Click" Text="Agregar" />
                </FooterTemplate>
            </asp:TemplateField>
        </Columns>
    </asp:GridView>
</asp:Content>
